# Component Governance pipeline.
# This pipeline is configured to run on weekly basis.
# Uses Tools\cgmanifest.json

trigger: none
pr: none

variables:
  runCodesignValidationInjection: ${{ false }}

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    # This is added by 1ES migration tool and it is okay to remove in the future.
    - ES365AIMigrationTooling

    sdl:
      componentgovernance:
        failOnAlert: true